root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/kubevirt-apiserver-proxy ."
  bin = "./tmp/kubevirt-apiserver-proxy"
  include_ext = ["go", "mod", "sum"]
  exclude_dir = ["tmp", "vendor", ".git", ".github"]
  delay = 500
  stop_on_error = true

[log]
  time = false

[misc]
  clean_on_exit = true
